import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { StudentProvider } from "./context/StudentContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "ClassTap",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Path to your favicon file in the public folder
    shortcut: "/favicon.ico",
    apple: "/favicon.png", // Optional for Apple devices
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StudentProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}
        </body>
      </StudentProvider>
    </html>
  );
}
